export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const SET_ITEMS_LOADER = "SET_ITEMS_LOADER";
export const GET_CATEGORIES_LOADER = "GET_CATEGORIES_LOADER";
